In [1]:
from methods.Basic.waveform_freq import waveform_freq

In [1]:
file_path = '/srv/scratch/z5459037/Data/test.wav'

In [3]:
arr, fs0  = waveform_freq(file_path, 16000)

In [4]:
arr.shape

(36480,)

In [5]:
fs0

48000

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from methods.Basic.smooth import smooth

arr1 = [[1, 2], [3, 4]]
# [2] and [[2, 2, 2], [1, 1, 1]] should fail
arr2 = [2, [2], [2, 2], [2, 2, 2], [[2, 2, 2], [1, 1, 1]], -2]

for _arr2 in arr2:
    try:
        print(smooth(arr1, _arr2, True))
        print()
    except Exception as e:
        print(e)
        print()

[[0.5 1. ]
 [2.  3. ]]

Kernel must be Integer or vector (length > 1). Instead got [2].

[[0.5 1. ]
 [2.  3. ]]

[[1.33333333 2.        ]
 [1.33333333 2.        ]]

Kernel must be Integer or vector (length > 1). Instead got [[2, 2, 2], [1, 1, 1]].

[[0.5 1. ]
 [2.  3. ]]



In [4]:
from methods.Basic.Landmarks_func import Landmarks_base, Localized_peaks,P_landmark

In [5]:
downsample_file = '/srv/scratch/z5459037/Data/test.wav'

In [6]:
thresholds = [10]
for thr in thresholds:
    print(thr)

10


In [7]:
obj1 = Landmarks_base(downsample_file)
[Fs, Y, T, Y_len, ms_s] = obj1.wav_read_info()

In [11]:
obj2 = Localized_peaks(obj1, thr=5)
[landmarks, pp_arr, pn_arr, peak_file] = obj2.localPeak()

/home/z5459037/Auto-Landmark/methods/Basic/Landmarks_func.py:189: RuntimeWarning: invalid value encountered in cast
  b_region = np.array(peak_file.loc[peak_file['transition'] != -2, ['start', 'end']]).astype(int)


In [12]:
len(pp_arr)

34

In [13]:
len(pn_arr)

37

In [6]:
landmarks

{'g+': array([0.033, 0.202, 0.451, 0.518, 0.683, 0.769, 0.861, 0.964, 1.174,
        1.324, 1.512, 1.692, 1.807, 1.896, 2.11 , 3.028, 3.101, 3.247,
        4.068, 4.16 , 4.306, 4.608, 5.309, 5.431, 5.554, 5.859, 5.983,
        6.106, 6.214, 6.401, 6.496, 6.569, 6.637, 6.725]),
 'g-': array([0.149, 0.401, 0.485, 0.577, 0.662, 0.749, 0.84 , 0.915, 1.039,
        1.154, 1.296, 1.436, 1.536, 1.651, 1.872, 2.691, 2.836, 2.971,
        3.081, 3.148, 3.764, 4.048, 4.138, 4.589, 5.288, 5.411, 5.509,
        5.594, 5.718, 5.839, 5.957, 6.085, 6.174, 6.451, 6.525, 6.701,
        6.811]),
 's+': array([0.99 , 3.103]),
 's-': array([4.1]),
 'b+': array([4.237]),
 'b-': array([], dtype=float64),
 'v+': array([], dtype=float64),
 'v-': array([], dtype=float64),
 'f+': array([], dtype=float64),
 'f-': array([], dtype=float64)}

In [8]:
len(landmarks['g-'])

37

In [9]:
len(landmarks['g+'])

34

In [6]:
p_base = P_landmark(obj1)

In [7]:
peak_file = p_base.find_P_landmark()

In [8]:
peak_file

time lmk  direction
0   2.066125  p+          1
1   3.238250  p+          1
2   4.305187  p+          1
3   4.640437  p+          1
0  26.965000  p-         -1
1  37.342500  p-         -1
2  46.101875  p-         -1
3  48.036875  p-         -1

In [12]:
import numpy as np

In [16]:
peak_file[peak_file['lmk']=='p+']['time']

0    2.066125
1    3.238250
2    4.305187
3    4.640437
Name: time, dtype: float64

In [21]:
test = {}
test['p+'] = np.array(peak_file[peak_file['lmk']=='p+']['time'])
test['p-'] = np.array(peak_file[peak_file['lmk']=='p+']['time'])

In [22]:
test

{'p+': array([2.066125 , 3.23825  , 4.3051875, 4.6404375]),
 'p-': array([2.066125 , 3.23825  , 4.3051875, 4.6404375])}

In [23]:
landmarks.update(test)

In [24]:
landmarks

{'g+': array([0.033, 0.202, 0.451, 0.518, 0.683, 0.769, 0.861, 0.964, 1.174,
        1.324, 1.512, 1.692, 1.807, 1.896, 2.11 , 3.028, 3.101, 3.247,
        4.068, 4.16 , 4.306, 4.608, 5.309, 5.431, 5.554, 5.859, 5.983,
        6.106, 6.214, 6.401, 6.496, 6.569, 6.637, 6.725]),
 'g-': array([0.149, 0.401, 0.485, 0.577, 0.662, 0.749, 0.84 , 0.915, 1.039,
        1.154, 1.296, 1.436, 1.536, 1.651, 1.872, 2.691, 2.836, 2.971,
        3.081, 3.148, 3.764, 4.048, 4.138, 4.589, 5.288, 5.411, 5.509,
        5.594, 5.718, 5.839, 5.957, 6.085, 6.174, 6.451, 6.525, 6.701,
        6.811]),
 's+': array([0.99 , 3.103]),
 's-': array([4.1]),
 'b+': array([4.237]),
 'b-': array([], dtype=float64),
 'v+': array([], dtype=float64),
 'v-': array([], dtype=float64),
 'f+': array([], dtype=float64),
 'f-': array([], dtype=float64),
 'p+': array([2.066125 , 3.23825  , 4.3051875, 4.6404375]),
 'p-': array([2.066125 , 3.23825  , 4.3051875, 4.6404375])}

In [2]:
from methods.Basic.Landmarks_func import extract_all_landmarks

In [14]:
landmarks = extract_all_landmarks(downsample_file, 10)

/home/z5459037/Auto-Landmark/methods/Basic/Landmarks_func.py:189: RuntimeWarning: invalid value encountered in cast
  b_region = np.array(peak_file.loc[peak_file['transition'] != -2, ['start', 'end']]).astype(int)


In [15]:
landmarks

{'g+': array([0.033, 0.202, 0.451, 0.518, 0.683, 0.769, 0.861, 0.964, 1.174,
        1.324, 1.512, 1.692, 1.807, 1.896, 2.11 , 3.028, 3.101, 3.247,
        4.068, 4.16 , 4.306, 4.608, 5.309, 5.431, 5.554, 5.859, 5.983,
        6.106, 6.214, 6.401, 6.496, 6.569, 6.637, 6.725]),
 'g-': array([0.149, 0.401, 0.485, 0.577, 0.662, 0.749, 0.84 , 0.915, 1.039,
        1.154, 1.296, 1.436, 1.536, 1.651, 1.872, 2.691, 2.836, 2.971,
        3.081, 3.148, 3.764, 4.048, 4.138, 4.589, 5.288, 5.411, 5.509,
        5.594, 5.718, 5.839, 5.957, 6.085, 6.174, 6.451, 6.525, 6.701,
        6.811]),
 's+': array([0.99 , 3.103]),
 's-': array([4.1]),
 'b+': array([4.237]),
 'b-': array([], dtype=float64),
 'v+': array([], dtype=float64),
 'v-': array([], dtype=float64),
 'f+': array([], dtype=float64),
 'f-': array([], dtype=float64),
 'p+': array([2.066125 , 3.23825  , 4.3051875, 4.6404375]),
 'p-': array([2.6965   , 3.73425  , 4.6101875, 4.8036875])}

In [2]:
import scipy

In [1]:
from methods.Advance.smooth import smooth

In [3]:
signal = scipy.io.loadmat('/home/z5459037/Auto-Landmark/methods/Advance/Audio_Signal.mat')

In [5]:
signal['Audio_Signal']

array([[-0.00152588],
       [-0.0020752 ],
       [-0.00183105],
       ...,
       [-0.01116943],
       [-0.01113892],
       [-0.01184082]])

In [22]:
input = signal['Audio_Signal']

In [23]:
input

array([[-0.00152588],
       [-0.0020752 ],
       [-0.00183105],
       ...,
       [-0.01116943],
       [-0.01113892],
       [-0.01184082]])

In [19]:
smooth_signal = smooth(input, -215)

In [20]:
smooth_signal[:9]

array([[ 9.11372297],
       [ 9.31844844],
       [ 9.52595787],
       [ 9.73641681],
       [ 9.95004279],
       [10.16709866],
       [10.38782536],
       [10.61240867],
       [10.84104705]])

In [21]:
from methods.Advance.hpfilt_std import hpfilt_std

In [25]:
hpsig = hpfilt_std(input, 16000, 'ADULT')

In [28]:
hpsig

array([[-0.00307636],
       [-0.00364508],
       [-0.00342032],
       ...,
       [-0.0064326 ],
       [-0.00646179],
       [-0.00722307]])