In [17]:
def pair_peaks(g_plus, g_minus):
    """
    Pair g+ and g- values such that each g+ is followed by a g-.

    :param g_plus: List of g+ values (sorted in ascending order)
    :param g_minus: List of g- values (sorted in ascending order)
    :return: Two lists containing paired g+ and g- values
    """

    g_plus_paired = []
    g_minus_paired = []

    i, j = 0, 0
    while i < len(g_plus) and j < len(g_minus):
        # If the current g+ value is less than the current g- value, add it to the paired list and move to the next g+
        if g_plus[i] < g_minus[j]:
            g_plus_paired.append(g_plus[i])
            i += 1
        # If the current g- value is less than the current g+ value, add it to the paired list and move to the next g-
        else:
            g_minus_paired.append(g_minus[j])
            j += 1

    # Ensuring we only retain pairs of g+ and g-, so the lists have equal length
    min_length = min(len(g_plus_paired), len(g_minus_paired))
    g_plus_paired = g_plus_paired[:min_length]
    g_minus_paired = g_minus_paired[:min_length]

    return g_plus_paired, g_minus_paired

# Usage example:
g_plus = [1.0, 2.5, 3.0, 4.5, 5.0]  # Replace with your g+ values
g_minus = [1.5, 3.5, 4.0, 5.5]  # Replace with your g- values

paired_g_plus, paired_g_minus = pair_peaks(g_plus, g_minus)
print(paired_g_plus)
print(paired_g_minus)

[1.0, 2.5, 3.0]
[1.5, 3.5, 4.0]


In [1]:
from methods.Basic.Landmarks_func import extract_all_landmarks

In [2]:
file = '/srv/scratch/z5459037/Data/test.wav'

In [3]:
landmarks = extract_all_landmarks(file, 10)

/home/z5459037/Auto-Landmark/methods/Basic/Landmarks_func.py:219: RuntimeWarning: invalid value encountered in cast
  b_region = np.array(peak_file.loc[peak_file['transition'] != -2, ['start', 'end']]).astype(int)


In [4]:
a = landmarks['g+']

In [8]:
landmarks

{'g+': array([0.033, 0.202, 0.451, 0.518, 0.683, 0.769, 0.861, 0.964, 1.174,
        1.324, 1.512, 1.692, 1.807, 1.896, 2.11 , 3.028, 3.101, 3.247,
        4.068, 4.16 , 4.306, 4.608, 5.309, 5.431, 5.554, 5.859, 5.983,
        6.106, 6.214, 6.401, 6.496, 6.569, 6.637, 6.725]),
 'g-': array([0.149, 0.401, 0.485, 0.577, 0.662, 0.749, 0.84 , 0.915, 1.039,
        1.154, 1.296, 1.436, 1.536, 1.651, 1.872, 2.691, 2.836, 2.971,
        3.081, 3.148, 3.764, 4.048, 4.138, 4.589, 5.288, 5.411, 5.509,
        5.594, 5.718, 5.839, 5.957, 6.085, 6.174, 6.451]),
 's+': array([0.99 , 3.103]),
 's-': array([4.1]),
 'b+': array([4.237]),
 'b-': array([], dtype=float64),
 'v+': array([], dtype=float64),
 'v-': array([], dtype=float64),
 'f+': array([], dtype=float64),
 'f-': array([], dtype=float64),
 'p+': array([2.066125 , 3.23825  , 4.3051875, 4.6404375]),
 'p-': array([2.6965   , 3.73425  , 4.6101875, 4.8036875])}

In [5]:
len(a)

34

In [6]:
b = landmarks['g-']

In [7]:
len(b)

34

In [28]:
c, d = pair_peaks(a, b)

In [29]:
len(c)

34

In [30]:
len(d)

34

In [34]:
np.array(c)

array([0.033, 0.202, 0.451, 0.518, 0.683, 0.769, 0.861, 0.964, 1.174,
       1.324, 1.512, 1.692, 1.807, 1.896, 2.11 , 3.028, 3.101, 3.247,
       4.068, 4.16 , 4.306, 4.608, 5.309, 5.431, 5.554, 5.859, 5.983,
       6.106, 6.214, 6.401, 6.496, 6.569, 6.637, 6.725])

In [35]:
np.array(d)

array([0.149, 0.401, 0.485, 0.577, 0.662, 0.749, 0.84 , 0.915, 1.039,
       1.154, 1.296, 1.436, 1.536, 1.651, 1.872, 2.691, 2.836, 2.971,
       3.081, 3.148, 3.764, 4.048, 4.138, 4.589, 5.288, 5.411, 5.509,
       5.594, 5.718, 5.839, 5.957, 6.085, 6.174, 6.451])

In [36]:
a

array([0.033, 0.202, 0.451, 0.518, 0.683, 0.769, 0.861, 0.964, 1.174,
       1.324, 1.512, 1.692, 1.807, 1.896, 2.11 , 3.028, 3.101, 3.247,
       4.068, 4.16 , 4.306, 4.608, 5.309, 5.431, 5.554, 5.859, 5.983,
       6.106, 6.214, 6.401, 6.496, 6.569, 6.637, 6.725])